FROM node:16

ENV MONGODB_CONNECTION_PROTOCOL mongodb+srv
ENV MONGODB_DB_NAME gh-demo
ENV MONGODB_CLUSTER_ADDRESS cluster1.1sa1unt.mongodb.net
ENV MONGODB_USERNAME bigjoe1992111
ENV MONGODB_PASSWORD joe28572418

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]